rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\arknights_processor.py" "D:\Code Base\Python Project\Multi Arkbot\main\arknights_processor.py"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\arknights_processor.py" "D:\Code Base\Python Project\Multi Arkbot\chenrui\arknights_processor.py"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\arknights_processor.py" "D:\Code Base\Python Project\Multi Arkbot\connor\arknights_processor.py"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\arknights_processor.py" "D:\Code Base\Python Project\Multi Arkbot\sam\arknights_processor.py"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\arknights_processor.py" "D:\Code Base\Python Project\Multi Arkbot\math\arknights_processor.py"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\arknights_processor.py" "D:\Code Base\Python Project\Multi Arkbot\bill\arknights_processor.py"

rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\settings.txt" "D:\Code Base\Python Project\Multi Arkbot\main\settings.txt"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\settings.txt" "D:\Code Base\Python Project\Multi Arkbot\chenrui\settings.txt"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\settings.txt" "D:\Code Base\Python Project\Multi Arkbot\connor\settings.txt"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\settings.txt" "D:\Code Base\Python Project\Multi Arkbot\sam\settings.txt"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\settings.txt" "D:\Code Base\Python Project\Multi Arkbot\math\settings.txt"
rem xcopy /y "D:\Code Base\Python Project\Arknight Autobot v2\settings.txt" "D:\Code Base\Python Project\Multi Arkbot\bill\settings.txt"


xcopy /y /e /h /i "E:\Code Base\Python Project\Arknight Autobot v2" "E:\Code Base\Python Project\Multi Arkbot\main"
xcopy /y /e /h /i "E:\Code Base\Python Project\Arknight Autobot v2" "E:\Code Base\Python Project\Multi Arkbot\chenrui"
xcopy /y /e /h /i "E:\Code Base\Python Project\Arknight Autobot v2" "E:\Code Base\Python Project\Multi Arkbot\connor"
xcopy /y /e /h /i "E:\Code Base\Python Project\Arknight Autobot v2" "E:\Code Base\Python Project\Multi Arkbot\sam"
xcopy /y /e /h /i "E:\Code Base\Python Project\Arknight Autobot v2" "E:\Code Base\Python Project\Multi Arkbot\math"
xcopy /y /e /h /i "E:\Code Base\Python Project\Arknight Autobot v2" "E:\Code Base\Python Project\Multi Arkbot\bill"